# setup toolchains

if (PLATFORM_VITA)
    if (NOT DEFINED CMAKE_TOOLCHAIN_FILE)
        if (DEFINED ENV{VITASDK})
            set(CMAKE_TOOLCHAIN_FILE "$ENV{VITASDK}/share/vita.toolchain.cmake" CACHE PATH "toolchain file")
        else ()
            message(FATAL_ERROR "Please define VITASDK to point to your SDK path!")
        endif ()
    endif ()
    include("$ENV{VITASDK}/share/vita.cmake" REQUIRED)
elseif (PLATFORM_SWITCH)
    if (DEFINED ENV{DEVKITPRO})
        set(DEVKITPRO $ENV{DEVKITPRO} CACHE STRING "DEVKITPRO" FORCE)
        if (NOT DEFINED CMAKE_TOOLCHAIN_FILE)
            set(CMAKE_TOOLCHAIN_FILE "${DEVKITPRO}/cmake/Switch.cmake" CACHE PATH "toolchain file")
        endif ()
    else ()
        message(FATAL_ERROR "Please define DEVKITPRO to point to your SDK path!")
    endif ()
else ()
    set(CMAKE_SYSTEM_NAME "Linux" CACHE STRING "" FORCE)
    set(CMAKE_SYSTEM_PROCESSOR "x86_64" CACHE STRING "" FORCE)
endif ()